<a href="https://colab.research.google.com/github/YasuharuSuzuki/25_programing1/blob/main/" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 7-2 continueとfor〜else
次のループへ移行するcontinueと、ループ終了時に実行する for 〜 else

## for文 参考サイト
### [参考サイト1 【Python早見表】 for文（反復処理）](https://chokkan.github.io/python/03control.html#for)
- for文、continue文、break文、for-else文が簡単にわかりやすく説明されています。

### [参考サイト2 【Python入門】for文による繰り返し](https://utokyo-ipp.github.io/3/3-2.html#for%E6%96%87%E3%81%AB%E3%82%88%E3%82%8B%E7%B9%B0%E3%82%8A%E8%BF%94%E3%81%97)
- こちらはfor文を中心に解説されています。練習問題もあります。

---
---
---

## continue文
- while文同様にfor文による繰り返し実行中にcontinue文を実行すると、以降の処理を実行せずに繰り返し処理を継続します。
- break文と比較するとあまり使わないです。比較的複雑なループ文で使うことが多いですかね

---

### サンプルプログラム4
- 変数 `num` を `12` で初期化し、for文で `23` までループします。rangeでループの終端番号を指定できますが、その数値-1までの値でループします。
- `num` が `3` の倍数の場合は `continue実行！ (num=n)` と表示して<b>continue文を実行</b>し、繰り返し処理を継続します。
- `num` が `3` の倍数以外の時は `for繰り返し中！ (num=n)` と表示します。(通常のループ処理を実行)
- ループを終了したら、最後に `for終了！ (num=n)` と表示します。for文ではループ終端番号として指定した数値-1の数字が出力されます

In [1]:
print("for開始！")
for num in range(12,23):
    if (num%3) == 0:
        print(f"continue実行！ (num={num})")
        continue
    print(f"for繰り返し中！ (num={num})")
print(f"for終了！ (num={num})")

for開始！
continue実行！ (num=12)
for繰り返し中！ (num=13)
for繰り返し中！ (num=14)
continue実行！ (num=15)
for繰り返し中！ (num=16)
for繰り返し中！ (num=17)
continue実行！ (num=18)
for繰り返し中！ (num=19)
for繰り返し中！ (num=20)
continue実行！ (num=21)
for繰り返し中！ (num=22)
for終了！ (num=22)


---

### 練習プログラム4 (15点)
- input()で初期値、ループ終端番号、continue倍数を空白区切りで受け取り、サンプルプログラム４のように表示するプログラムを作成してみましょう
  - 最初に`for開始！ (init_num=n, loop_end=n, continue_pow=n)` と出力します。初期値とループ終端番号、continue倍数も表示しましょう。（nは実際の初期値とループ終端番号とcontinue倍数）
  - for文の中で `num` が `continue_pow` の倍数の場合は `continue実行！ (num=n)` と表示して<b>continue文を実行</b>し、繰り返し処理を継続します。
  - continue を実行しない時は `num` がループ終端番号になるまでの間、`for繰り返し中！ (num=n)` を出力します。（nは現在の数値）
  - ループを終了したら、最後に `for終了！ (num=n)` と表示します。

#### こちら↓にプログラムを記述しましょう

for開始！ (init_num=108, loop_end=116, continue_pow=4)
continue実行！ (num=108)
for繰り返し中！ (num=109)
for繰り返し中！ (num=110)
for繰り返し中！ (num=111)
continue実行！ (num=112)
for繰り返し中！ (num=113)
for繰り返し中！ (num=114)
for繰り返し中！ (num=115)
for終了！ (num=115)


- continue倍の時だけcontinueが実行され、すぐに次のループを実行します。

### 💡 練習プログラム4 ヒント
- 減点になる方は、input()で受け取った初期値が反映されていないケースが多いです
- 初期値はrangeで指定できます([参考 : Python早見表 - for文（反復処理）](https://chokkan.github.io/python/03control.html#for))
- それよりは少ないですが、ループ回数やcontinue倍数が反映されておらずに減点されるケースも見受けられます

#### 📤 出力結果のヒント

「こちら↓にプログラムを記述しましょう」のセルの下に以下のような出力結果のサンプルがあります

```
for開始！ (init_num=108, loop_end=116, continue_pow=4)
continue実行！ (num=108)
for繰り返し中！ (num=109)
for繰り返し中！ (num=110)
for繰り返し中！ (num=111)
continue実行！ (num=112)
for繰り返し中！ (num=113)
for繰り返し中！ (num=114)
for繰り返し中！ (num=115)
for終了！ (num=115)
```

こちらは以下の入力値の場合の出力期待値になります。

##### 🔢入力値

```
108 116 4
```

同じ入力が与えられた時の出力結果として参考になるので活用しましょう  
消えてしまった方はGithubのソースを見ると良いでしょう  

In [ ]:
#@title 送信処理用共通プログラム（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown 解答の送信に必要です。（中身は絶対に修正しないでください）

import os
os.makedirs(".client/python", exist_ok=True)  # 隠しフォルダを作成
!wget -q https://raw.githubusercontent.com/YasuharuSuzuki/25_programing1/feature/add_class01/91_notebook_client/src/setup.sh -O .client/setup.sh   # 外部コードをダウンロードして隠しフォルダに配置
!chmod +x ./.client/setup.sh
!bash ./.client/setup.sh # 実行

# モジュールの初期化
exec(open('.client/client_setup.py').read())

# ノートブック固有の設定
NOTEBOOK_PATH = "07_for文/02_continueとfor〜else.ipynb"
set_notebook_config(NOTEBOOK_PATH)

🔧 ローカル開発環境(sandbox) セットアップ中...
✅ ローカル開発環境(sandbox) セットアップ完了

📝 注意事項:
   - Notebookで exec(open('.client/client_setup.py').read()) を実行してください
   - 環境設定は .env / .envrc ファイルで管理されます
🚀 共通プログラム初期化中...
✅ 保存済みメールアドレス取得: ptt1245@okiu.ac.jp
送信ボタン用関数が読み込まれました（問題番号別送信ボタン検索・Notebook構造解析・localStorage/ファイル保存対応・送信時自動保存）
🔧 採点システムURL設定: http://localhost:8080
🔧 採点システムURL: http://localhost:8080
✅ 送信機能の初期化完了
📋 ノートブックパス: 07_for文/02_continueとfor〜else.ipynb
✅ グローバル設定に保存しました


In [2]:
#@title 問4 送信ボタン表示（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown メールアドレスを取得して、送信ボタンを押してください（中のプログラムは絶対に修正しないでください）
display(create_submit_button(problem_number=4))

🔧 採点システムURL設定: http://localhost:8080
📋 ノートブックパス設定: 07_for文/02_continueとfor〜else.ipynb
🎯 保存済みメールアドレスを自動設定: ptt1245@okiu.ac.jp


---
---
---

## for 〜 else文
- while文同様にfor文による繰り返しを終了した後で実行する処理をelseブロックにて記述することが出来ます。
- break文によってループを中断した時はelseブロックは実行されません。
- 普段ほとんど使用しませんが、ループを全部終わらせた時に実行させたい処理がある時に使うことがあります。

## サンプルプログラム5
- input()でbreak番号を受け取り、サンプルプログラム3のように表示するサンプルプログラムです
  - 最初に`for開始！ (break_num=n)` と出力します。break番号も表示しているので確認しましょう。（nは実際のbreak番号）
  - forループ内で `num` が `break_num` になるとif文が実行され、`break実行！ループを抜けます (num=n)` と表示したあと<b>break文を実行</b>してループを抜けます。この時はelse文は実行されません。
  - breakしない間は `for繰り返し中！ (num=n)` と表示します。
  - breakせずにループを終了した場合は `for 〜 elseブロック実行！ (num=n)` と表示します
  - for 〜 else 後、またはbreak文によりforループを抜けると `for終了！ (num=n)` と表示します。

In [3]:
break_num = int(input())
print(f"for開始！ (break_num={break_num})")
for num in range(2,9):
    if num >= break_num:
        print(f"break実行！ループを抜けます (num={num})")
        break
    print(f"for繰り返し中！ (num={num})")
else:
    print(f"for 〜 elseブロック実行！ (num={num})")
print(f"for終了！ (num={num})")

for開始！ (break_num=6)
for繰り返し中！ (num=2)
for繰り返し中！ (num=3)
for繰り返し中！ (num=4)
for繰り返し中！ (num=5)
break実行！ループを抜けます (num=6)
for終了！ (num=6)


### 説明
- input()にてbreak番号を受け取り、break_numに格納します。
- `for開始! (break_num=n)` でループを開始します
- `num` が `break_num` になるまでの間、`for繰り返し中！ (num=n)` が実行されます。
- break番号が `9` より小さい場合
  - `num` がbreak番号になるとif文の中が実行され、`break実行！ループを抜けます (num=n)` と表示したあと<b>break文を実行</b>してループを抜けます。
  - この時は<b>for 〜 elseブロックが実行されない</b>
- break番号が `9` 以上の場合
  - この時はbreakが実行されないため<b>for 〜 elseブロックが実行</b>され、`for 〜 elseブロック実行！ (num=n)` と表示します。
- forループを抜けたあと `for終了！ (num=n)` と表示します。

---

## 練習プログラム5 (15点)
- input()でループ終端番号と２つの倍数を受け取り、それぞれの倍数の時に決まった文字列を出力するプログラムを作成してみましょう。
  - input()でループ終端番号、倍数1、倍数2を空白区切りのint値で受け取ります。
  - `for開始！ (loop_end=n, pow1=n, pow2=n)` と出力します。ループ回数、倍数1、倍数2も表示しましょう。（nは実際のループ終端番号と倍数２つ）

- `num` は初期値1から開始し、倍数1の倍数になった時は`Fizz！ (num=n)`、倍数2の倍数になった時は`Buzz！ (num=n)`、倍数1と倍数2両方の倍数になった時は`FizzBuzz！ (num=n, fizz_buzz_count=n)`と出力します
  - `fizz_buzz_count` については、倍数1と倍数2両方の倍数になった回数を表示してください。
  - どちらの倍数にもならない場合は `for繰り返し中！ (num=n)` と表示します。
- FizzBuzzの表示回数が5回に達した時は `break実行！ループを抜けます (num=n)` と表示後にbreak文を実行してループを抜けます。
- break文を実行せずにループを終了した場合は `for 〜 elseブロック実行！ (num=n)` と表示します。
- for 〜 else 後、またはbreak文によりforループを抜けたら、`for終了！ (num=n)` と表示してください。

#### こちら↓にプログラムを記述しましょう

for開始！ (loop_end=25、pow1=2、pow2=3)
for繰り返し中！ (num=1)
Fizz！ (num=2)
Buzz！ (num=3)
Fizz！ (num=4)
for繰り返し中！ (num=5)
FizzBuzz！ (num=6、fizz_buzz_count=1)
for繰り返し中！ (num=7)
Fizz！ (num=8)
Buzz！ (num=9)
Fizz！ (num=10)
for繰り返し中！ (num=11)
FizzBuzz！ (num=12、fizz_buzz_count=2)
for繰り返し中！ (num=13)
Fizz！ (num=14)
Buzz！ (num=15)
Fizz！ (num=16)
for繰り返し中！ (num=17)
FizzBuzz！ (num=18、fizz_buzz_count=3)
for繰り返し中！ (num=19)
Fizz！ (num=20)
Buzz！ (num=21)
Fizz！ (num=22)
for繰り返し中！ (num=23)
FizzBuzz！ (num=24、fizz_buzz_count=4)
for 〜 elseブロック実行！ (num=24)
for終了！ (num=24)


#### 💡 練習プログラム5　ヒント
FizzBuzz難しいと思うのですが、以下の手順でじっくり考えてみましょう
1. 受け取ったループ回数でループするプログラムを作りましょう
2. 次に受け取った倍数1と倍数2を使って "Fizz"と"Buzz"、"FizzBuzz"を表示するプログラムを作りましょう
3. 次に "FizzBuzz" の表示回数をカウントするプログラムを作りましょう
4. 次に "FizzBuzz" の表示回数が5回になったらbreakを実行するプログラムを作りましょう。メッセージも忘れずに。
5. 最後に else 文を作って、メッセージを出力するプログラムを作りましょう

##### 👩‍🔬　動作確認
1. 動作確認してみましょう。`35 2 3` と入力して、2の倍数の時に"Fizz"、3の倍数の時に"Buzz"、6の倍数のときに"FizzBuzz"と出力されることを確認しましょう。30でbreakが実行されることも確認しましょう。break時のメッセージが表示されるはずです。
2. 次に `25 2 3` と入力して、else文が実行されることを確認しましょう。else時のメッセージが表示されるはずです。

##### 📤　出力結果のヒント

「こちら↓にプログラムを記述しましょう」のセルの下に以下のような出力結果のサンプルがあります

```
for開始！ (loop_end=25、pow1=2、pow2=3)
for繰り返し中！ (num=1)
Fizz！ (num=2)
Buzz！ (num=3)
Fizz！ (num=4)
for繰り返し中！ (num=5)
FizzBuzz！ (num=6、fizz_buzz_count=1)
for繰り返し中！ (num=7)
Fizz！ (num=8)
Buzz！ (num=9)
Fizz！ (num=10)
for繰り返し中！ (num=11)
　︰
（途中略）
　︰
FizzBuzz！ (num=24、fizz_buzz_count=4)
for 〜 elseブロック実行！ (num=24)
for終了！ (num=24)

```

こちらは以下の入力値の場合の出力期待値になります。

##### 🔢入力値

```
25 2 3
```

同じ入力が与えられた時の出力結果として参考になるので活用しましょう  
消えてしまった方はGithubのソースを見ると良いでしょう  

In [7]:
#@title 問5 送信ボタン表示（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown メールアドレスを取得して、送信ボタンを押してください（中のプログラムは絶対に修正しないでください）
display(create_submit_button(problem_number=5))

🔧 採点システムURL設定: http://localhost:8080
📋 ノートブックパス設定: 07_for文/02_continueとfor〜else.ipynb
🎯 保存済みメールアドレスを自動設定: ptt1245@okiu.ac.jp


---
---
---

## for文のネスト
- for文の中にfor文を書くと2重ループのプログラムを書くことが出来ます。

### 多重リスト
- リストの要素としてリストを指定することもできます。リストを要素とするリストは多重リストと呼ばれます。次は二重リストの例です。

```python
lns = [['a', 'b', 'c'], ['aaa', 'bbb', 'ccc'], [10, 20, 30]]
```

- 多重リストの要素指定は複数のインデックスで行います。 前の例で外側の [] で示されるリストの2番目の要素のリスト、 すなわち ['aaa', 'bbb', 'ccc'] の最初の要素は次のように指定します。

```python
lns[1][0]
```

---
```
aaa
```
---

### サンプルプログラム6
- 2重ループを使用して、2重のリストを表示するサンプルプログラムです

In [5]:
list1 = [['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i'], ['j', 'k', 'l']]

for y in range(4):
    for x in range(3):
        print(f'list1の{y+1}番目の要素（リスト）の{x+1}番目の要素 = {list1[y][x]}')

list1の1番目の要素（リスト）の1番目の要素 = a
list1の1番目の要素（リスト）の2番目の要素 = b
list1の1番目の要素（リスト）の3番目の要素 = c
list1の2番目の要素（リスト）の1番目の要素 = d
list1の2番目の要素（リスト）の2番目の要素 = e
list1の2番目の要素（リスト）の3番目の要素 = f
list1の3番目の要素（リスト）の1番目の要素 = g
list1の3番目の要素（リスト）の2番目の要素 = h
list1の3番目の要素（リスト）の3番目の要素 = i
list1の4番目の要素（リスト）の1番目の要素 = j
list1の4番目の要素（リスト）の2番目の要素 = k
list1の4番目の要素（リスト）の3番目の要素 = l


### 練習プログラム6 (15点)
- 2重ループを使って”突然の死”ジェネレータを作ってみましょう
- [突然の死とは](https://dic.nicovideo.jp/a/%E7%AA%81%E7%84%B6%E3%81%AE%E6%AD%BB)(興味ある方だけ)

サンプル「突然の死」

＿人人人人人人＿   
＞　突然の死　＜   
￣Y^Y^Y^Y^Y￣   

- 「突然の死」の部分はinput()で文字列を受け取り、好きな文字を入れることが出来るように作りましょう。
- 文字数に応じて上下の文字も増やして表示しましょう（文字入力は全角文字前提でOKです）
- 2重ループを使うために1文字ずつ出力してみましょう

### 入力例1
---
```
突然の死
```
---

### 出力例1
---

```
＿人人人人人人＿
＞　突然の死　＜
￣Y^Y^Y^Y^Y￣
```

---
---

### 入力例2
---
```
ゆたしくうにげーさびら！
```
---

### 出力例2
---
```
＿人人人人人人人人人人人人人人＿
＞　ゆたしくうにげーさびら！　＜
￣Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y￣
```
---
- 上記のように文字列が長くなった時は、それに応じて周囲の装飾も長くしましょう
---
---

### ここ↓にPythonコードを記述してください

＿人人人人人人人人人人人人人人＿
＞　ゆたしくうにげーさびら！　＜
￣Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y^Y￣


#### 💡 練習プログラム6　ヒント
突然の死ジェネレータも結構難しいと思いますが、以下の手順でじっくり考えてみましょう
1. 受け取った文字列を関数 len() に渡して文字数を取得しましょう
2. 一行目 "＿人"から始まって、"人"を文字数分連結し、最後を "人＿" とした文字列を作成します
3. 二行目 "＞　"から始まり、真ん中に入力文字列、最後を "　＜" とした文字列を作成します
4. 三行目 "￣"から始まり、"Y^"を文字数分連結し、最後を "Y￣" とした文字列を作成します
5. サンプルプログラム6のように二重ループで出力して完成です

##### 👩‍🔬 動作確認
1. 動作確認してみましょう。入力例1のように `突然の死` と入力して、出力例1と出力結果が同じになるかを確認しましょう。
2. 次に入力例2のように `ゆたしくうにげーさびら！` と入力して、出力例2と出力結果が同じになるかを確認しましょう。

In [28]:
#@title 問6 送信ボタン表示（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown メールアドレスを取得して、送信ボタンを押してください（中のプログラムは絶対に修正しないでください）
display(create_submit_button(problem_number=6))

🔧 採点システムURL設定: http://localhost:8080
📋 ノートブックパス設定: 07_for文/02_continueとfor〜else.ipynb
🎯 保存済みメールアドレスを自動設定: ptt1245@okiu.ac.jp
